# Generated by Django 6.0 on 2025-12-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio_line1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio_line2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio_line3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio_line4',
        ),
        migrations.AddField(
            model_name='profile',
            name='hero_bio',
            field=models.TextField(default='A web designer & backend developer based in India.'),
        ),
    ]
