# Generated by Django 6.0 on 2025-12-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_bio_line1_remove_profile_bio_line2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#a5b4fc', max_length=7)),
                ('background_color', models.CharField(default='#0a0a0a', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('heading_font', models.CharField(default='DM Sans', max_length=50)),
                ('body_font', models.CharField(default='DM Sans', max_length=50)),
                ('show_background_circles', models.BooleanField(default=True)),
                ('circle_color', models.CharField(default='#6366f1', max_length=7)),
                ('button_style', models.CharField(default='rounded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#6366f1', max_length=7)),
                ('secondary_color', models.CharField(default='#a5b4fc', max_length=7)),
                ('background_color', models.CharField(default='#0a0a0a', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('heading_font', models.CharField(choices=[('DM Sans', 'DM Sans'), ('Inter', 'Inter'), ('Poppins', 'Poppins'), ('Roboto', 'Roboto'), ('Montserrat', 'Montserrat'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato')], default='DM Sans', max_length=50)),
                ('body_font', models.CharField(choices=[('DM Sans', 'DM Sans'), ('Inter', 'Inter'), ('Poppins', 'Poppins'), ('Roboto', 'Roboto'), ('Montserrat', 'Montserrat'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato')], default='DM Sans', max_length=50)),
                ('show_intro_section', models.BooleanField(default=True)),
                ('show_about_section', models.BooleanField(default=True)),
                ('show_skills_section', models.BooleanField(default=True)),
                ('show_works_section', models.BooleanField(default=True)),
                ('show_contact_section', models.BooleanField(default=True)),
                ('show_background_circles', models.BooleanField(default=True)),
                ('circle_color', models.CharField(default='#6366f1', max_length=7)),
                ('button_style', models.CharField(choices=[('rounded', 'Rounded'), ('pill', 'Pill'), ('square', 'Square')], default='rounded', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
