# Generated by Django 6.0 on 2025-12-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_savedtheme_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='body_font',
            field=models.CharField(choices=[('DM Serif Display', 'DM Serif Display'), ('Public Sans', 'Public Sans'), ('DM Sans', 'DM Sans'), ('Inter', 'Inter'), ('Poppins', 'Poppins'), ('Roboto', 'Roboto'), ('Montserrat', 'Montserrat'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato')], default='Public Sans', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='heading_font',
            field=models.CharField(choices=[('DM Serif Display', 'DM Serif Display'), ('Public Sans', 'Public Sans'), ('DM Sans', 'DM Sans'), ('Inter', 'Inter'), ('Poppins', 'Poppins'), ('Roboto', 'Roboto'), ('Montserrat', 'Montserrat'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato')], default='DM Serif Display', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='primary_color',
            field=models.CharField(default='#eabe7c', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='secondary_color',
            field=models.CharField(default='#23967f', max_length=7),
        ),
    ]
