# Generated by Django 6.0 on 2025-12-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_sitesettings_body_font_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedtheme',
            name='show_background_circles',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='show_background_circles',
        ),
        migrations.AddField(
            model_name='savedtheme',
            name='background_style',
            field=models.CharField(default='circles', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='background_style',
            field=models.CharField(choices=[('none', 'No Effect'), ('circles', 'Moving Circles'), ('particles', 'Tech Particles'), ('gradient', 'Gradient Mesh'), ('grid', 'Retro Grid')], default='circles', max_length=20),
        ),
    ]
