# Generated by Django 6.0 on 2025-12-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_savedtheme_show_background_circles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='background_style',
            field=models.CharField(choices=[('none', 'No Effect'), ('circles', 'Moving Circles'), ('particles', 'Tech Particles'), ('gradient', 'Gradient Mesh'), ('grid', 'Retro Grid'), ('waves', 'Digital Waves'), ('matrix', 'Matrix Rain'), ('starfield', 'Starfield Warp'), ('aurora', 'Aurora Borealis'), ('hexagons', 'Neon Hexagons')], default='circles', max_length=20),
        ),
    ]
