# Generated by Django 6.0 on 2025-12-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_sitesettings_background_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
