# Generated by Django 6.0 on 2025-12-23 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_project_description_skill_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='greeting_font_size',
            field=models.FloatField(default=2.0),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='name_font_size',
            field=models.FloatField(default=11.0),
        ),
    ]
