# Generated by Django 6.0 on 2025-12-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_sitesettings_greeting_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_assistant_script',
            field=models.TextField(blank=True, default='', help_text='Paste the full JS script from your AI provider here'),
        ),
    ]
