# Generated by Django 6.0 on 2025-12-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_ai_assistant_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='greeting_font_size_mobile',
            field=models.FloatField(default=1.5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='name_font_size_mobile',
            field=models.FloatField(default=4.0),
        ),
    ]
