# Generated by Django 6.0 on 2025-12-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_customsection_customitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsection',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
