# Generated by Django 6.0 on 2025-12-25 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customsection_is_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admin User (Deprecated)'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customsection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expertise',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expertise_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedtheme',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_themes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customsection',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='greeting',
            field=models.CharField(default='Hi, I am', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Your Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('leetcode', 'LeetCode'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('dribbble', 'Dribbble'), ('behance', 'Behance'), ('medium', 'Medium'), ('devto', 'Dev.to'), ('stackoverflow', 'Stack Overflow'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='customsection',
            unique_together={('user', 'slug')},
        ),
        migrations.AddIndex(
            model_name='contactinfo',
            index=models.Index(fields=['user'], name='app_contact_user_id_ba179c_idx'),
        ),
        migrations.AddIndex(
            model_name='customsection',
            index=models.Index(fields=['user'], name='app_customs_user_id_dcd3c7_idx'),
        ),
        migrations.AddIndex(
            model_name='education',
            index=models.Index(fields=['user'], name='app_educati_user_id_1c79cd_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['user'], name='app_experie_user_id_2fbcc3_idx'),
        ),
        migrations.AddIndex(
            model_name='expertise',
            index=models.Index(fields=['user'], name='app_experti_user_id_153a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='app_profile_user_id_afb92c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user'], name='app_project_user_id_ab83eb_idx'),
        ),
        migrations.AddIndex(
            model_name='savedtheme',
            index=models.Index(fields=['user'], name='app_savedth_user_id_b87039_idx'),
        ),
        migrations.AddIndex(
            model_name='sitesettings',
            index=models.Index(fields=['user'], name='app_siteset_user_id_b36576_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['user'], name='app_skill_user_id_f30621_idx'),
        ),
        migrations.AddIndex(
            model_name='sociallink',
            index=models.Index(fields=['user'], name='app_sociall_user_id_2c74e4_idx'),
        ),
    ]
