# Generated by Django 6.0 on 2025-12-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_assign_existing_data_to_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsection',
            name='button_text',
            field=models.CharField(default='View Details', help_text='Text for the link button', max_length=50),
        ),
        migrations.AddField(
            model_name='customsection',
            name='card_layout',
            field=models.CharField(choices=[('grid', 'Grid (Cards)'), ('list', 'List View'), ('timeline', 'Timeline')], default='grid', max_length=20),
        ),
        migrations.AddField(
            model_name='customsection',
            name='show_image',
            field=models.BooleanField(default=True, help_text='Show image/icon in card'),
        ),
        migrations.AddField(
            model_name='customsection',
            name='show_link_button',
            field=models.BooleanField(default=True, help_text='Show clickable link button'),
        ),
    ]
