# Generated by Django 6.0 on 2025-12-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_customsection_button_text_customsection_card_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='section_heading_color',
            field=models.CharField(default='#ffffff', help_text='Color for section titles (About, Skills, etc.)', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_heading_font_size',
            field=models.FloatField(default=1.6, help_text='Font size in rem for section headings'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='section_heading_font_size_mobile',
            field=models.FloatField(default=1.4, help_text='Font size in rem for section headings on mobile'),
        ),
    ]
