# Generated by Django 6.0 on 2025-12-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_sitesettings_section_heading_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='text_color',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='general_text_color',
            field=models.CharField(default='#a0a0a0', help_text='Color for headings, greeting, section titles', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_about_text_color',
            field=models.CharField(default='#ffffff', help_text='Color for hero bio and about description', max_length=7),
        ),
    ]
