# Generated by Django 6.0 on 2025-12-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_sitesettings_text_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
