# Generated by Django 6.0 on 2025-12-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_sociallink_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.CharField(blank=True, help_text='Path to preview image in static/', max_length=200)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this theme is available for selection')),
                ('default_config', models.JSONField(blank=True, default=dict)),
                ('css_file', models.CharField(blank=True, help_text='e.g., css/themes/terminal-x.css', max_length=100)),
                ('js_file', models.CharField(blank=True, help_text='e.g., js/themes/terminal-x.js', max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='active_theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('terminal_x', 'Terminal X'), ('neural_odyssey', 'Neural Odyssey'), ('chrono_story', 'Chrono Story'), ('glass_horizon', 'Glass Horizon'), ('cinematic_flow', 'Cinematic Flow')], default='classic', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_config',
            field=models.JSONField(blank=True, default=dict, help_text='Theme-specific configuration'),
        ),
    ]
