# Generated by Django 6.0 on 2025-12-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_sitesettings_active_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='active_theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('interactive_3d', 'Interactive 3D'), ('neural_odyssey', 'Neural Odyssey'), ('chrono_story', 'Chrono Story'), ('glass_horizon', 'Glass Horizon'), ('cinematic_flow', 'Cinematic Flow')], default='classic', max_length=30),
        ),
    ]
