# Generated by Django 6.0 on 2025-12-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_sitesettings_active_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedtheme',
            name='greeting_font_size',
            field=models.FloatField(default=1.3),
        ),
        migrations.AddField(
            model_name='savedtheme',
            name='name_font_size',
            field=models.FloatField(default=4.5),
        ),
        migrations.AddField(
            model_name='savedtheme',
            name='section_heading_font_size',
            field=models.FloatField(default=1.0),
        ),
    ]
