# Generated by Django 6.0 on 2025-12-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_add_font_sizes_to_savedtheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='experience',
            name='position',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timeframe',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='active_theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('interactive_3d', 'Interactive 3D'), ('developer_folio', 'Developer Folio'), ('irish_spring', 'Irish Spring'), ('neural_odyssey', 'Neural Odyssey'), ('chrono_story', 'Chrono Story'), ('glass_horizon', 'Glass Horizon'), ('cinematic_flow', 'Cinematic Flow')], default='classic', max_length=30),
        ),
    ]
