# Generated by Django 6.0 on 2026-01-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_add_pageview_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='active_theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('interactive_3d', 'Interactive 3D'), ('developer_folio', 'Developer Folio'), ('irish_spring', 'Irish Spring'), ('neural_odyssey', 'Neural Odyssey'), ('chrono_story', 'Chrono Story'), ('glass_horizon', 'Glass Horizon'), ('cinematic_flow', 'Cinematic Flow'), ('vcard', 'VCard Professional')], default='classic', max_length=30),
        ),
    ]
