# Generated by Django 6.0 on 2026-01-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_add_victoreke_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_bg_color',
            field=models.CharField(default='#6366f1', help_text='Favicon background color', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_design',
            field=models.CharField(choices=[('circle', 'Circle'), ('rounded', 'Rounded Square'), ('square', 'Square'), ('gradient', 'Gradient'), ('outline', 'Outline')], default='circle', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_initials',
            field=models.CharField(blank=True, default='', help_text='1-3 characters for favicon (e.g., AB)', max_length=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon_text_color',
            field=models.CharField(default='#ffffff', help_text='Favicon text color', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='active_theme',
            field=models.CharField(choices=[('modern', 'Modern Minimalist'), ('classic', 'Classic Professional'), ('creative', 'Creative Dark'), ('developer', 'Developer Folio'), ('terminal', 'Terminal/Hacker'), ('terminal_x', 'Terminal X (Advanced)'), ('interactive_3d', 'Interactive 3D'), ('vcard', 'Digital Business Card'), ('cv_simple', 'CV / Resume Simple'), ('irish_spring', 'Irish Spring'), ('victoreke', 'Victor Eke Portfolio'), ('binil', 'TheGr8Binil')], default='classic', max_length=30),
        ),
    ]
