# Generated by Django 6.0 on 2026-01-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_add_favicon_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='intro_greetings',
            field=models.TextField(blank=True, default='Hello,Bonjour,Hola,Привет,مرحبا,നമസ്കാരം,こんにちは,नमस्ते', help_text='Comma-separated list of greetings to display'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intro_speed',
            field=models.CharField(choices=[('slow', 'Slow'), ('medium', 'Medium'), ('fast', 'Fast')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_intro_animation',
            field=models.BooleanField(default=True, help_text='Show language greetings animation on page load'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='active_theme',
            field=models.CharField(choices=[('modern', 'Modern Minimalist'), ('classic', 'Classic'), ('creative', 'Creative Dark'), ('developer', 'Developer Folio'), ('terminal', 'Terminal/Hacker'), ('terminal_x', 'Terminal X (Advanced)'), ('interactive_3d', 'Interactive 3D'), ('vcard', 'Digital Business Card'), ('cv_simple', 'CV / Resume Simple'), ('irish_spring', 'Irish Spring'), ('victoreke', 'Victor Eke Portfolio'), ('binil', 'TheGr8Binil')], default='classic', max_length=30),
        ),
    ]
