# Generated by Django 6.0 on 2026-01-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_add_intro_animation_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='last_seen_version',
            field=models.CharField(default='0.0.0', help_text='Last version of the app the user has seen release notes for', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='active_theme',
            field=models.CharField(choices=[('modern', 'Modern Minimalist'), ('classic', 'Classic'), ('creative', 'Creative Dark'), ('developer', 'Developer Folio'), ('terminal', 'Terminal/Hacker'), ('terminal_x', 'Terminal X (Advanced)'), ('interactive_3d', 'Interactive 3D'), ('vcard', 'Digital Business Card'), ('cv_simple', 'CV / Resume Simple'), ('irish_spring', 'Irish Spring'), ('victoreke', 'Pro V2'), ('binil', 'TheGr8Binil')], default='classic', max_length=30),
        ),
    ]
